export const PERMISSIONS = {
  ASSETS_VIEW_ASSETS: { value: "view_assets", type: "read" },
  ASSETS_MANAGE_ASSETS: { value: "manage_assets", type: "read" },
  ASSETS_ASSIGNED_UNASSIGNED: { value: "assigned_unassigned", type: "read" },
  ASSETS_ASSIGNED_ASSETS: { value: "assigned_assets", type: "read" },

  TICKETS_MANAGE_TICKETS: { value: "manage_tickets", type: "read" },
  TICKETS_RAISE_TICKET: { value: "raise_ticket", type: "read" },
  TICKETS_TICKET_SETTINGS: { value: "ticket_settings", type: "read" },
  TICKETS_REPORTS: { value: "ticket_reports", type: "read" },
  TICKETS_TEAM_MEMBERS: { value: "tickets_team_members", type: "read" },

  TASKS_MY_TASKS: { value: "my_tasks", type: "read" },
  TASKS_DEPARTMENT_TASKS: { value: "department_tasks", type: "read" },
  TASKS_TEAM_MEMBERS: { value: "task_team_members", type: "read" },
  TASKS_REPORTS: { value: "task_reports", type: "read" },
  TASKS_SETTINGS: { value: "task_settings", type: "read" },

  VISITORS_ADD_VISITOR: { value: "add_visitor", type: "read" },
  VISITORS_ADD_CLIENT: { value: "add_client", type: "read" },
  VISITORS_MANAGE_VISITORS: { value: "manage_visitors", type: "read" },
  VISITORS_TEAM_MEMBERS: { value: "visitor_team_members", type: "read" },
  VISITORS_REPORTS: { value: "visitor_reports", type: "read" },

  FINANCE_CASHFLOW: { value: "cashflow", type: "read" },
  FINANCE_FINANCE: { value: "finance_finance", type: "read" },
  FINANCE_BILLING: { value: "billing", type: "read" },
  FINANCE_MIX_BAG: { value: "finance_mix_bag", type: "read" },
  FINANCE_DATA: { value: "finance_data", type: "read" },
  FINANCE_SETTINGS: { value: "finance_settings", type: "read" },

  SALES_TURNOVER: { value: "turnover", type: "read" },
  SALES_FINANCE: { value: "sales_finance", type: "read" },
  SALES_MIX_BAG: { value: "sales_mix_bag", type: "read" },
  SALES_DATA: { value: "sales_data", type: "read" },
  SALES_SETTINGS: { value: "sales_settings", type: "read" },

  HR_EMPLOYEE: { value: "employee", type: "read" },
  HR_COMPANY: { value: "company", type: "read" },
  HR_FINANCE: { value: "hr_finance", type: "read" },
  HR_MIX_BAG: { value: "hr_mix_bag", type: "read" },
  HR_DATA: { value: "hr_data", type: "read" },
  HR_SETTINGS: { value: "hr_settings", type: "read" },
  HR_EMPLOYEE_EDIT: {
    value: "hr_employee_edit",
    type: "write",
    access: "button",
  },

  ADMIN_ANNUAL_EXPENSES: { value: "admin_annual_expenses", type: "read" },
  ADMIN_INVENTORY: { value: "admin_inventory", type: "read" },
  ADMIN_FINANCE: { value: "admin_finance", type: "read" },
  ADMIN_MIX_BAG: { value: "admin_mix_bag", type: "read" },
  ADMIN_DATA: { value: "admin_data", type: "read" },
  ADMIN_SETTINGS: { value: "admin_settings", type: "read" },

  MAINTENANCE_ANNUAL_EXPENSES: {
    value: "maintenance_annual_expenses",
    type: "read",
  },
  MAINTENANCE_INVENTORY: { value: "maintenance_inventory", type: "read" },
  MAINTENANCE_FINANCE: { value: "maintenance_finance", type: "read" },
  MAINTENANCE_MIX_BAG: { value: "maintenance_mix_bag", type: "read" },
  MAINTENANCE_DATA: { value: "maintenance_data", type: "read" },
  MAINTENANCE_SETTINGS: { value: "maintenance_settings", type: "read" },

  IT_ANNUAL_EXPENSES: { value: "it_annual_expenses", type: "read" },
  IT_INVENTORY: { value: "it_inventory", type: "read" },
  IT_FINANCE: { value: "it_finance", type: "read" },
  IT_MIX_BAG: { value: "it_mix_bag", type: "read" },
  IT_DATA: { value: "it_data", type: "read" },
  IT_SETTINGS: { value: "it_settings", type: "read" },
};
